"""empty message

Revision ID: 05be6984683f
Revises: 30dc5b8cb13b
Create Date: 2022-10-31 23:27:39.124385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05be6984683f'
down_revision = '30dc5b8cb13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Person', 'person_fav_id')
    op.add_column('Person_To_Favorites', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Person_To_Favorites', 'User', ['user_id'], ['id'])
    op.drop_column('Planet', 'planet_fav_id')
    op.add_column('Planet_To_Favorites', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Planet_To_Favorites', 'User', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Planet_To_Favorites', type_='foreignkey')
    op.drop_column('Planet_To_Favorites', 'user_id')
    op.add_column('Planet', sa.Column('planet_fav_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Person_To_Favorites', type_='foreignkey')
    op.drop_column('Person_To_Favorites', 'user_id')
    op.add_column('Person', sa.Column('person_fav_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
