"""empty message

Revision ID: d742622f85c8
Revises: b69cbf0979cd
Create Date: 2022-11-01 00:04:25.838569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd742622f85c8'
down_revision = 'b69cbf0979cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_to_person',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['Person.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    op.drop_table('Planet_To_Favorites')
    op.drop_table('Person_To_Favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Person_To_Favorites',
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['Person.id'], name='Person_To_Favorites_person_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='Person_To_Favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('person_id', name='Person_To_Favorites_pkey')
    )
    op.create_table('Planet_To_Favorites',
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['Planet.id'], name='Planet_To_Favorites_planet_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='Planet_To_Favorites_user_id_fkey'),
    sa.PrimaryKeyConstraint('planet_id', name='Planet_To_Favorites_pkey')
    )
    op.drop_table('user_to_person')
    # ### end Alembic commands ###
