"""empty message

Revision ID: e653b8f0d9db
Revises: dfc5d9be53cc
Create Date: 2022-11-01 00:15:13.251109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e653b8f0d9db'
down_revision = 'dfc5d9be53cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Vehicle_To_Favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Vehicle_To_Favorites',
    sa.Column('vehicle_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], name='Vehicle_To_Favorites_user_id_fkey'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['Vehicle.id'], name='Vehicle_To_Favorites_vehicle_id_fkey'),
    sa.PrimaryKeyConstraint('vehicle_id', 'user_id', name='Vehicle_To_Favorites_pkey')
    )
    # ### end Alembic commands ###
